#cloud-config
# /var/log/cloud-init-output.log - cloud init logs (this script)

# /etc/apache2/sites-available
# /var/www/html
# sudo systemctl restart apache

# scp dave@hoverflytest39.westeurope.cloudapp.azure.com:/home/dave/php.ini .

# https://www.journaldev.com/24954/install-wordpress-on-ubuntu  (suggests Maria)
# https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-ubuntu-18-04
package_upgrade: true
runcmd:
  # Apache
  - sudo apt update -y
  - sudo apt install apache2 -y

  # get helper files from repo
  - cd /home/dave
  - sudo git clone https://github.com/djhmateer/hoverfly-website.git source

  # AllowOverride in web root
  - sudo cp /home/dave/source/infra/000-default.conf /etc/apache2/sites-available

  - sudo a2enmod rewrite

  # mysql
  - sudo apt install mysql-server -y

  # should i do this?
  #- sudo mysql_secure_installation

  - sudo mysql -e "CREATE DATABASE wordpress;"
  - sudo mysql -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -e "GRANT ALL ON wordpress.* TO 'wp_user'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -e "FLUSH PRIVILEGES;"

  # php
  - sudo apt install php libapache2-mod-php php-mysql -y
  - sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip -y

  # create info.php and delete the apache default index.html
  - sudo cp /home/dave/source/infra/info.php /var/www/html
  - sudo rm /var/www/html/index.html

  - sudo systemctl restart apache2
  
  # checks for syntax errors in apache conf
  - sudo apache2ctl configtest
  - sudo systemctl restart apache2


  # Wordpress CLI
  # https://www.linode.com/docs/websites/cms/wordpress/install-wordpress-using-wp-cli-on-ubuntu-18-04/
  - cd ~ 
  - sudo curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - sudo chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp

  - cd /var/www/
  - sudo chown -R www-data:www-data html
  - cd html
  - sudo -u www-data wp core download
  - sudo -u www-data wp core config --dbname='wordpress' --dbuser='wp_user' --dbpass='password' --dbhost='localhost' --dbprefix='wp_'

  # I need the domain name eg http://hoverflytest427.westeurope.cloudapp.azure.com/
  - sudo chmod 777 /home/dave/source/infra/wpcoreinstall.sh
  - ./wpcoreinstall.sh
  # - sudo -u www-data wp core install --url='http://example.com' --title='Blog Title' --admin_user='dave' --admin_password='letmein' --admin_email='email@domain.com'

  #**TODO plugins

  # wordpress
  # - cd /tmp 
  # - curl -O https://wordpress.org/latest.tar.gz
  # - tar -xvf latest.tar.gz
  # - sudo cp -a /tmp/wordpress/. /var/www/html

  # # this has pre-baked in database settings
  # # also updates to max_filesize for restoring a website
  # - sudo cp /home/dave/source/infra/wp-config.php /var/www/html/

  # - sudo chown -R www-data:www-data /var/www/html
  # - sudo chmod -R 755 /var/www/html

  # - sudo mkdir /var/www/html/wp-content/uploads
  # - sudo chown -R www-data:www-data /var/www/html/wp-content/uploads/

  # - curl -s https://api.wordpress.org/secret-key/1.1/salt/
  # - sudo nano /var/www/wordpress/wp-config.php

  # settings needed for wp all in one website import
  # https://help.servmask.com/2018/10/27/how-to-increase-maximum-upload-file-size-in-wordpress/
  # .htaccess works, but not auto generated until after wordpress starts
  # wp-config.php putting in settings didn't work for me
  # so php.ini works
  # **WILL NEED TO PATCH IN NEW VERSION WHEN NEW VERSION OF PHP**
  - cd /etc/php/7.2/apache2
  - sudo cp php.ini phpoldini.txt
  - sudo cp /home/dave/source/infra/php.ini /etc/php/7.2/apache2/php.ini

  - sudo systemctl restart apache2

final_message: "The system is finally up, after $UPTIME seconds"

  #
  # Bashtop
  #
  # - echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list
  # - sudo wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
  # - sudo apt update -y
  # - sudo apt install bashtop -y

# make a quick test page to signify that the server is ready to go
  # - cd /var/www/cookie-dave-web
  # - echo "Healthy" > healthcheck.html

# OS updates need a reboot 
  # - sudo reboot now