#cloud-config
# /var/log/cloud-init-output.log - cloud init logs (this script)

# /etc/apache2/sites-available
# /var/www/html
# sudo systemctl restart apache

# https://www.journaldev.com/24954/install-wordpress-on-ubuntu  (suggests Maria)
# https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-ubuntu-18-04
package_upgrade: true
runcmd:
  # apache
  - sudo apt update -y
  - sudo apt install apache2 -y

  # get helper files from repo
  - cd /home/dave
  - sudo git clone https://github.com/djhmateer/hoverfly-website.git source

  # mysql
  - sudo apt install mysql-server -y

  # should i do this?
  #- sudo mysql_secure_installation

  - sudo mysql -e "CREATE DATABASE wordpress;"
  - sudo mysql -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -e "GRANT ALL ON wordpress.* TO 'wp_user'@'localhost' IDENTIFIED BY 'password';"

  # php
  - sudo apt install php libapache2-mod-php php-mysql -y

  # - sudo apt install php-cli

  # info.php and delete the apache default index.html
  - sudo cp /home/dave/source/infra/info.php /var/www/html
  - sudo rm /var/www/html/index.html

  - sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip -y
  - sudo systemctl restart apache2

  # /etc/apache2/sites-available/000-default.conf
  # /var/www/wordpress doc root
  # AllowOverride
  - sudo cp /home/dave/source/infra/000-default.conf /etc/apache2/sites-available

  - sudo a2enmod rewrite

  # checks for syntax errors in apache conf
  - sudo apache2ctl configtest
  - sudo systemctl restart apache2

  # wordpress
  - cd /tmp 
  - curl -O https://wordpress.org/latest.tar.gz
  - tar -xvf latest.tar.gz
  - sudo cp -a /tmp/wordpress/. /var/www/html

  # - touch /tmp/wordpress/.htaccess
  # - cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php
  # - mkdir /tmp/wordpress/wp-content/upgrade
  # - sudo cp -a /tmp/wordpress/. /var/www/wordpress

  - sudo chown -R www-data:www-data /var/www/html
  - sudo chmod -R 755 /var/www/html

  - sudo mkdir /var/www/html/wp-content/uploads
  - sudo chown -R www-data:www-data /var/www/html/wp-content/uploads/

  # - curl -s https://api.wordpress.org/secret-key/1.1/salt/
  # - sudo nano /var/www/wordpress/wp-config.php

  # settings needed for wp all in one website import
  - sudo cp /var/www/html/.htaccess oldhtaccess
  - sudo sh -c "echo 'php_value upload_max_filesize 512MB' >> /var/www/html/.htaccess"
  - sudo sh -c "echo 'php_value post_max_size 512MB' >> /var/www/html/.htaccess"
  - sudo sh -c "echo 'php_value memory_limit 256MB' >> /var/www/html/.htaccess"
  - sudo sh -c "echo 'php_value max_execution_time 300' >> /var/www/html/.htaccess"
  - sudo sh -c "echo 'php_value max_input_time 300' >> /var/www/html/.htaccess"

  - sudo systemctl restart apache2
  #
  # Bashtop
  #
  # - echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list
  # - sudo wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
  # - sudo apt update -y
  # - sudo apt install bashtop -y

# make a quick test page to signify that the server is ready to go
  # - cd /var/www/cookie-dave-web
  # - echo "Healthy" > healthcheck.html

# OS updates need a reboot 
  # - sudo reboot now